server:
  context-path: /seller
  port: 8082

rpc:
  manager:
    url: http://localhost:8081/manager/
  client:
    url:  http://localhost:8081/manager/
    basePackage: com.lh.api

spring:
  cache:
    type: hazelcast
  datasource:
    url: jdbc:mysql://118.126.111.144:3306/seller?user=root&password=my-secret-pw&useUnicode=true&characterEncoding=utf-8
  jpa:
      show-sql: true
  activemq:
    broker-url: tcp://118.126.111.144:61616
    packages:
      trust-all: true

logging:
  level:
    com.googlecode.jsonrpc4j: debug

