server:
  context-path: /seller
  port: 8082

# 需要以/结尾
rpc.manager.url: http://localhost:8081/manager/

spring:
  datasource:
    url: jdbc:mysql://118.126.111.144:3306/manager?user=root&password=my-secret-pw&useUnicode=true&characterEncoding=utf-8
  jpa:
      show-sql: true