spring:
  datasource:
    url: jdbc:mysql://118.126.111.144:3306/manager?user=root&password=my-secret-pw&useUnicode=true&characterEncoding=utf-8
  jpa:
      show-sql: true
server:
  context-path: /manager
  port: 8081